const endpoints = {
    allProducts: "allproducts",
    getBrands: "getBrands",
    getProductsByBrands:"getproductsbyBrands",
    getCategory:"getCategory",
    getProductsByCategory:"getproductsbycategory",
    getSubCategory:"getSubCategory",
    getProductsBySubCategory:"getproductsbysubcategory",
    selectProduct:"selectproduct",
    searchProduct:"searchproduct",
    postCartSaveItem:"postCartSaveItem",
    deleteCartItem:"deleteCartItem",
    getSavedCartItems:"getSaveCartItems",
    postCreateCustomer:"postCreateCustomer",
    postLoginCustomer:"postLoginCustomer",
    quantityIncrement:"QuantityIncrement",
    quantityDecrement:"QuantityDecrement",
    postOrderHistoryDetail:"postOrderHistoryDetail",
    postCreateDeliveryAddress:"postCreateDeliveryAddress",
    postDeleteDeliveryAddress:"postDeleteDeliveryAddress",
    getDeliveryAddress:"getDeliveryAddress",
    getDeliveryAddressForUpdate:"getDeliveryAddressForUpdate",
    postUpdateDeliveryAddress:"postUpdateDeliveryAddress",
    postPlacedSingleOrder:"postPlacedOrder",
    postPlacedMultipleOrder:"postPlacedOrderMulti",
    postCnfOrderDetail:"postCnfOrderDetail",
}

export { endpoints };